import type { IndexHealthItem, IndexVerdict } from "../ipc/types";

export const fmtBytes = (n: number): string => {
  if (n < 1024) return `${n} B`;
  const u = ["KB", "MB", "GB", "TB"];
  let v = n / 1024;
  let i = 0;
  while (v >= 1024 && i < u.length - 1) {
    v /= 1024;
    i++;
  }
  return `${v < 10 ? v.toFixed(1) : Math.round(v)} ${u[i]}`;
};

export const VERDICT_LABEL: Record<IndexVerdict, string> = {
  used: "USED",
  keep: "KEEP",
  review: "REVIEW",
  candidate: "DROP?",
};

export const VERDICT_ORDER: IndexVerdict[] = ["candidate", "review", "keep", "used"];

/** Bytes recoverable if every candidate were dropped. Deliberately excludes
 *  `review` — uniqueness is a guarantee someone may be relying on silently. */
export const recoverable = (items: IndexHealthItem[]): number =>
  items.filter((i) => i.verdict === "candidate").reduce((a, b) => a + b.bytes, 0);

/**
 * A DROP script for the candidates.
 *
 * CONCURRENTLY because dropping an index on a live table takes an ACCESS
 * EXCLUSIVE lock otherwise, and this database has tables with three million
 * rows. It cannot run inside a transaction, which is why there is no BEGIN
 * here — and why the header says so rather than letting someone discover it
 * by pasting the script into a transaction block and watching it fail.
 *
 * One statement per physical index: a logical index spanning 290 partitions
 * is 290 drops, and pretending otherwise would produce a script that errors
 * on the first line.
 */
export function dropScript(items: IndexHealthItem[]): string {
  const cands = items.filter((i) => i.verdict === "candidate");
  if (cands.length === 0) return "-- No candidates. Nothing to drop.\n";
  const lines: string[] = [
    "-- Generated by TupleNest. Review every line before running.",
    "--",
    "-- These indexes have not been scanned since the statistics were last",
    "-- reset. That is not the same as unused: a reset, a replica that serves",
    "-- the reads, or a rare-but-critical monthly report will all look like",
    "-- zero here. Confirm against your own workload first.",
    "--",
    "-- DROP INDEX CONCURRENTLY cannot run inside a transaction block.",
    "-- Run these as individual statements, not wrapped in BEGIN/COMMIT.",
    "",
  ];
  for (const c of cands) {
    lines.push(
      `-- ${c.schema}.${c.table} (${c.columns}) — ${c.size}, ${c.members} index(es), ${c.scans} scans`,
    );
    // Identifiers arrive already schema-qualified and quoted by quote_ident.
    for (const id of c.indexIdents) lines.push(`DROP INDEX CONCURRENTLY IF EXISTS ${id};`);
    lines.push("");
  }
  return lines.join("\n");
}
